// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOYqEuG1KxKLA5it7NIw3rJRo6Hhbpvc',
    appId: '1:706201912501:web:83ce8c54ac169a60efeafc',
    messagingSenderId: '706201912501',
    projectId: 'bandw-80b62',
    authDomain: 'bandw-80b62.firebaseapp.com',
    storageBucket: 'bandw-80b62.firebasestorage.app',
    measurementId: 'G-S53H9XY55S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_FD6DSIElKotxaiuPLVG9eqekg8LcglE',
    appId: '1:706201912501:android:af0ff1eab102bd5eefeafc',
    messagingSenderId: '706201912501',
    projectId: 'bandw-80b62',
    storageBucket: 'bandw-80b62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrhC4S6GmtLhMWov4ADkYQWMfM16HnkWg',
    appId: '1:706201912501:ios:335b4e710c0cb7e4efeafc',
    messagingSenderId: '706201912501',
    projectId: 'bandw-80b62',
    storageBucket: 'bandw-80b62.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );
}
